### ISSUE TITLE
Running new noresm testlist on betzy

### ISSUE THREAD

**Issue by mvertens** [NorESMhub/CTSM#91]
### Brief summary of bug
Using noresm2_5_alpha06 with a new proposed CLM test suite for noresm - I am getting errors like the following in numerous FATES tests:

```
  Case dir: /cluster/home/mvertens/noresm/ctsm_testing/ERP_D_Ld10_P64x2.f10_f10_mg37.IHistClm60BgcCrop.betzy_intel.clm-default.20241014_144301_kznjgk
    Errors were:
        Building test for ERP in directory /cluster/work/users/mvertens/noresm/ctsm_testing/ERP_D_Ld10_P64x2.f10_f10_mg37.IHistClm60BgcCrop.betzy_intel.clm-default.20241014_144301_kznjgk
        NOTE: LND_TUNING_MODE is clm6_0_GSWP3v1 which is NOT tuned, but is based on clm5_0_GSWP3v1
        NOTE: LND_TUNING_MODE is clm6_0_GSWP3v1 which is NOT tuned, but is based on clm5_0_GSWP3v1
        /cluster/projects/nn10013k/mvertens/src/noresm2_5_alpha07_v1/components/clm/src/utils/clmfates_interfaceMod.F90(890): error #6460: This is not a component name that is defined in the encompassing structure.   [PFT_AREAFRAC_LU]

        /cluster/projects/nn10013k/mvertens/src/noresm2_5_alpha07_v1/components/clm/src/utils/clmfates_interfaceMod.F90(890): error #6366: The shapes of the array expressions do not conform.

        /cluster/projects/nn10013k/mvertens/src/noresm2_5_alpha07_v1/components/clm/src/utils/clmfates_interfaceMod.F90(891): error #6460: This is not a component name that is defined in the encompassing structure.   [BAREGROUNDFRAC]

        /cluster/projects/nn10013k/mvertens/src/noresm2_5_alpha07_v1/components/clm/src/utils/clmfates_interfaceMod.F90(2021): error #6460: This is not a component name that is defined in the encompassing structure.   [FLUSH_ALL_HVARS]

        ERROR: BUILD FAIL: clm.buildlib failed, cat /cluster/home/mvertens/noresm/ctsm_testing/ERP_D_Ld10_P64x2.f10_f10_mg37.IHistClm60BgcCrop.betzy_intel.clm-default.20241014_144301_kznjgk/bld/lnd.bldlog.241014-145702
```

**Comment by mvertens** [comment]
This now works with ctsm5.3.008 and fates sci.1.78.3_api.36.1.0_noresm_v0.
